<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pl</string>
	</array>
	<key>name</key>
	<string>Prolog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#clausecontents</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-zA-Z][a-zA-Z0-9_]*\(((?'parameters'(?'number'\d+)|(?'underscore'_)|(?'list'\[(\g'parameters'(,\g'parameters')*?(\|\g'parameters')?)??\])|(?'atom'[a-z][a-zA-Z0-9_]*)|(?'variable'[A-Z][a-zA-Z0-9_]*)|(?'compound'\g'atom'\(\g'parameters'(,\g'parameters')*?\)))(,\g'parameters')*)\))[\s^\n]*(:-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.head.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[.^%]*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.clauseend.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clause.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#clausecontents</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.clause.body.prolog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*[a-zA-Z][a-zA-Z0-9_]*\(.*?\)[\s^\n]*\.</string>
			<key>name</key>
			<string>entity.name.function.fact.prolog</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>clausecontents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%.*</string>
					<key>name</key>
					<string>comment.line.percent-sign.prolog</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(-&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.flow.if.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.flow.else.prolog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.if.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>meta.if.body.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>!</string>
					<key>name</key>
					<string>keyword.control.cut.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s(is)\s)|((?&lt;!\w)_)|==|=|\\\+|&gt;|&lt;|\+|\*|\-</string>
					<key>name</key>
					<string>keyword.operator.prolog</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.prolog</string>
	<key>uuid</key>
	<string>df89928b-6612-475a-b414-f319d9b98664</string>
</dict>
</plist>
