<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.</string>
	<key>fileTypes</key>
	<array>
		<string>pl</string>
		<string>pro</string>
	</array>
	<key>name</key>
	<string>Prolog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(:-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.clause.bodybegin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[.^%]*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.clause.bodyend.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clause.body.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controlandkeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.clause.body.prolog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-zA-Z][a-zA-Z0-9_]*\()(?=.*:-.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clause.headbegin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))(?=\s*:-)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clause.headend.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clause.head.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z][a-zA-Z0-9_]*\()(?=.*--&gt;.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dcg.headbegin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))(?=\s*--&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dcg.headend.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dcg.head.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(--&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dcg.bodybegin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[.^%]*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dcg.bodyend.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dcg.body.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controlandkeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.dcg.body.prolog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>TODO match newlines</string>
			<key>match</key>
			<string>\s*[a-zA-Z][a-zA-Z0-9_]*\([^\.]*\)[\s^\n]*\.</string>
			<key>name</key>
			<string>entity.name.function.fact.prolog</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>atom</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9_])[a-z][a-zA-Z0-9_]*(?!\s*\(|[a-zA-Z0-9_])</string>
					<key>name</key>
					<string>constant.other.atom.simple.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'.*?'</string>
					<key>name</key>
					<string>constant.other.atom.quoted.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[\]</string>
					<key>name</key>
					<string>constant.other.atom.emptylist.prolog</string>
				</dict>
			</array>
		</dict>
		<key>builtin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(op|findall|write|nl|test)\b</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%.*</string>
					<key>name</key>
					<string>comment.line.percent-sign.prolog</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.prolog</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z]|/)\d+</string>
					<key>name</key>
					<string>constant.numeric.integer.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.prolog</string>
				</dict>
			</array>
		</dict>
		<key>controlandkeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(-&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.if.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.else.prolog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.if.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#builtin</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#atom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>meta.if.body.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>!</string>
					<key>name</key>
					<string>keyword.control.cut.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s(is)\s)|=:=|==|=|\\\+|&gt;|&lt;|\+|\*|\-</string>
					<key>name</key>
					<string>keyword.operator.prolog</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9_])[A-Z][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.parameter.uppercase.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)_</string>
					<key>name</key>
					<string>variable.language.anonymous.prolog</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.prolog</string>
	<key>uuid</key>
	<string>df89928b-6612-475a-b414-f319d9b98664</string>
</dict>
</plist>
